name: 'Ligretto Bots build, push and deploy'

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: 'eu-north-1'

jobs:
  ligretto-bot-clj-image:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Docker Setup QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: 'arm64'
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760

        - name: Docker login
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            platforms: linux/arm64
            push: true
            tags: |
              ghcr.io/memebattle/ligretto-bot-clj:${{ github.sha }}
              ghcr.io/memebattle/ligretto-bot-clj:latest
            context: '.'
            file: 'Dockerfile'
            cache-from: type=gha,scope=$GITHUB_REF_NAME-ligretto-bot-clj
            cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME-ligretto-bot-clj